name: Manual

on:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum

      - name: Run
        run: |
          mkdir -p result
          go test -bench=. --ldflags="-checklinkname=0" > result/result.txt || echo "Run failed but proceeding."

      - name: Generate Report
        run: go run result/result.go

      - name: Update README
        run: |
          echo "### Test Results Summary" > temp_summary.md
          tail -n 10 result/result.txt >> temp_summary.md
          echo "" >> temp_summary.md
          echo "Full results are available in result/result.txt." >> temp_summary.md
          cat temp_summary.md >> README.md
        if: always() # Ensure this step runs even if previous ones fail
