name: Manual

on:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
          cache-dependency-path: go.sum

      - name: Run
        run: |
          mkdir -p result
          go test -bench=. --ldflags="-checklinkname=0" > result/result.txt || echo "Run failed but proceeding."

      - name: Generate Report
        run: go run result/result.go

      - name: Print README.md to Summary
        run: |
          echo "### README.md Content" >> $GITHUB_STEP_SUMMARY
          cat README.md >> $GITHUB_STEP_SUMMARY
        if: always() # Run even if previous steps fail
